# -*- coding: utf-8 -*-
"""DecisionTree+Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wk16AZDyMwsWDNldGb6rSbDvidww5B2H
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

data=load_iris()
df= pd.DataFrame(data.data, columns=data.feature_names)
df.head()

df["target"]=data["target"]
df.head()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(df.drop("target", axis="columns"), df['target'], test_size=0.2, random_state=420)

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_train, y_train)

from sklearn import tree
tree.plot_tree(model)
plt.show()