# -*- coding: utf-8 -*-
"""AiWeek1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/SpencerBar/Sheridan/blob/master/Year%202/Ai%26ML/AiWeek1.ipynb
"""

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from sklearn.metrics import r2_score, mean_squared_error

data = pd.read_csv("happiness.csv")

data.head()

data.describe

features = data[['Happiness Score']]

features

label = data[['Happiness Rank']]

x_train, x_test, y_train, y_test = train_test_split(features, label, test_size = 0.2, random_state = 546)

model = LinearRegression()

model.fit(x_train, y_train)

predictions = model.predict(x_test)

predictions

model.predict([[7.4]])

r2_score(y_test, predictions)