# -*- coding: utf-8 -*-
"""llm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JpIvzi-oiy_OJzm23LylXOGytGKJiREj
"""

pip install transformers

from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("distilgpt2")
model = AutoModelForCausalLM.from_pretrained("distilgpt2")

text = "The Shawshank"

input = tokenizer.encode(text=text, return_tensors="pt")
output = model.generate(input, max_length=100, do_sample=True)
print(tokenizer.decode(output[0]))